# Generated by Django 5.0.6 on 2024-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
