# Generated by Django 5.0.6 on 2024-05-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_postitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
