# Generated by Django 5.0.6 on 2024-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_postitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
