# Generated by Django 5.0.6 on 2024-05-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_postitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='slug',
            field=models.CharField(default='default-slug', max_length=50),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
