# Generated by Django 5.0.6 on 2024-05-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_postitem_slug_alter_postitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
