# Generated by Django 5.0.6 on 2024-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_postitem_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='subtitle',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
