# Generated by Django 5.0.6 on 2024-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_postitem_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='subtitle',
            field=models.TextField(max_length=700),
        ),
    ]
