# Generated by Django 5.0.6 on 2024-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_postitem_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=700)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(default='default-slug', max_length=50)),
                ('banner', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
            ],
        ),
    ]
