# Generated by Django 5.0.6 on 2024-06-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='github',
            field=models.CharField(default='https://www.github.com/alexkuznecov16', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='date',
            field=models.DateField(),
        ),
    ]
